### ISSUE TITLE
Yautja Tracker Not Tracking Items in Containers

### ISSUE THREAD

**Issue by LunaMayn** [cmss13-devs/cmss13#4163]
### Testmerges

#4003, #4151, #4156

### Description of the bug

The predator gear tracking verb does not seem to be able to track bodies while they are in containers, and the signature simply disappears.

### What's the difference with what should have happened?

The predator gear tracker should track both bodies and gear anywhere in the map that isn't in possession of a Predator or on the Predator ship.

### How do we reproduce this bug?

1. Kill a Predator
2. Stuff him in a crate/bodybag
3. Try the gear tracker option, the body will not be tracked

### Issue Bingo

- [ ] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [ ] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)
